# Generated by Django 4.0.3 on 2022-04-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at'], 'verbose_name': 'Trabalho', 'verbose_name_plural': 'Trabalhos'},
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=450),
        ),
        migrations.AlterField(
            model_name='job',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
